

INSERT INTO PR2_DEPTO
(DEPT_NO, NOMBRE, LOCALIZACION) 
VALUES  (10, 'COMERCIAL', 'C/JUAN BRAVO, 10, MADRID');

INSERT INTO PR2_DEPTO VALUES 
(20, 'MARKETING', 'C/JUAN BRAVO, 10, MADRID');

INSERT INTO PR2_DEPTO 
VALUES 
(30, 'FINANZAS', NULL);

INSERT INTO PR2_DEPTO 
(DEPT_NO, NOMBRE)
VALUES 
(40, 'RRHH');

INSERT INTO PR2_EMPLE
(EMP_NO, APELLIDO, OFICIO, FECHA_ALT, SALARIO, COMISION, DEPT_NO)
VALUES (7999, 'GARCÍA', 'DIRECTOR', '02/03/2016', 3500, 1000, 10);


INSERT INTO PR2_EMPLE
VALUES (8000, 'RODRÍGUEZ', 'COMERCIAL', 7999, '12/05/2017', 1500.8, NULL, 10);

INSERT INTO PR2_DEPTO
(LOCALIZACION, NOMBRE, DEPT_NO) 
VALUES 
('SEVILLA', 'IT', 50);

INSERT INTO PR2_DEPTO
(DEPT_NO, LOCALIZACION, NOMBRE) 
VALUES 
(60, 'BARCELONA', 'LEGAL');


DNI VARCHAR2(9) CONSTRAINT UQ_PR2_CLI_DNI UNIQUE,
    NOMBRE VARCHAR2(20) CONSTRAINT NN_PR2_CLI_NOM NOT NULL,
--ACTIVIDAD
CREATE TABLE PR3_CLIENTE (
COD_CLI NUMBER (4) CONSTRAINT CLI_COD_CLI_PK PRIMARY KEY,
DNI VARCHAR2(9) CONSTRAINT UQ_PR3_CLI_DNI UNIQUE,
NOMBRE VARCHAR2(20) CONSTRAINT NN_PR3_CLI_NOM NOT NULL,
APELLIDO1 VARCHAR2(15) CONSTRAINT APE1_NN NOT NULL,
APELLIDO2 VARCHAR2(15) CONSTRAINT APE2_NN NOT NULL
);

Identifica los errores:
INSERT INTO PR3_CLIENTE VALUES (1,'12345678Q', 'PEDRO', 'PASCUAL', 'GARCÍA'); 
INSERT INTO PR2_CLIENTE VALUES (2,'12345678Q', 'SARA', 'GÓNZALEZ', 'ORTEGA'); 
INSERT INTO PR2_CLIENTE 
(COD_CLI, DNI, NOMBRE, APELLIDO1)
VALUES (2,'12345678R', 'JESÚS', 'RODRÍGUEZ', NULL); 
INSERT INTO PR3_CLIENTE VALUES (1,'12345678H', 'JESÚS', 'RODRÍGUEZ', 'LÓPEZ');

--ACTIVIDAD 2
CREATE TABLE PR2_ARTICULO (
COD_ART NUMBER(7) CONSTRAINT ART_COD_ART_PK PRIMARY KEY,
NOMBRE VARCHAR2(25) CONSTRAINT ART_NOM_CH CHECK (NOMBRE IN ('TORNILLO', 'TUERCA', 'TACO', 'DESTORNILLADOR', 'MARTILLO', 'CLAVO')),
PRECIO NUMBER(11,2) DEFAULT 3.5,
FECHA_ALT DATE DEFAULT SYSDATE); 

Identifica los errores:
INSERT INTO PR2_ARTICULO (COD_ART, NOMBRE, PRECIO) 
VALUES (1, 'TORNILLO', 0.12); bien

INSERT INTO PR2_ARTICULO (COD_ART, NOMBRE, PRECIO) 
VALUES (2, 'CLAVO', 0.525);

INSERT INTO PR2_ARTICULO (COD_ART, NOMBRE, PRECIO) 
VALUES (3, 'ALICATES', 5); DECIMAL - ALICATES NOS ESTA

INSERT INTO PR2_ARTICULO (COD_ART, NOMBRE, PRECIO) 
VALUES (4, 'MARTILLO', NULL);
.............


CREATE TABLE PR2_COMPRA (
	COD_CLI NUMBER (4) CONSTRAINT NN_PR2_COMP_COD_CLI NOT NULL,
	COD_ART NUMBER(7) CONSTRAINT NN_PR2_COMP_COD_ART NOT NULL,
	CANTIDAD NUMBER(8) CONSTRAINT NN_PR2_COMP_COD_CANTIDAD NOT NULL,
	FECHA_COMPRA DATE DEFAULT SYSDATE,
	CONSTRAINT PK_PR2_COM_COD_CLI_COD_ART PRIMARY KEY (COD_CLI,COD_ART),
	CONSTRAINT FK_PR2_COM_COD_CLI FOREIGN KEY (COD_CLI) REFERENCES PR2_CLIENTE(COD_CLI),
	CONSTRAINT FK_PR2_COM_COD_ART FOREIGN KEY (COD_ART) REFERENCES PR2_ARTICULO(COD_ART)
); 

INSERT INTO PR2_COMPRA 
(COD_CLI, COD_ART, CANTIDAD) 

VALUES (1234, 3, 2);

INSERT INTO PR2_COMPRA 
(COD_CLI, COD_ART, CANTIDAD, FECHA_COMPRA) 

VALUES (1, '', 2, ' ');

